name: mac on web
on:
  workflow_dispatch:
    inputs:
      response_id:
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: source script-mac-web.sh
        env:
          response_id: ${{ inputs.response_id }}
      - run: sleep 1000000
