name: XvFB on linux on Web
on:
  workflow_dispatch:
    inputs:
      response_id:
        required: false
        default: ""
      callback_url:
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: source script-xvfb.sh
        env:
          response_id: ${{ inputs.response_id }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          callback_url: ${{ inputs.callback_url }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@master
        env:
          response_id: ${{ inputs.response_id }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          callback_url: ${{ inputs.callback_url }}
