name: web-linux
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
        with:
          detached: true
          connect-timeout-seconds: 21600
      - name: print tmate session
        run: |
          /tmp/tmate/tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
      - name: print tmate session
        run: |
          url=`/tmp/tmate/tmate -S /tmp/tmate.sock display -p '#{tmate_web}' |jq "@uri" -jRr `; echo $url
