name: web-linux
on:
  workflow_dispatch:
    inputs:
      response_id:
        required: false
        default: ""
      callback_url:
        required: false
        default: ""
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create web version of tmate
        run: source script-linux-web.sh
        env:
          response_id: ${{ inputs.response_id }}
          callback_url: ${{ inputs.callback_url }}
      - run: sleep 1000000
